### ISSUE TITLE
ps4database.xml path is messed up

### ISSUE THREAD

**Issue by jogolden** [jogolden/GhidraPS4Loader#1]
Since Ghidra is an absolute pain in the ass to develop plugins/loaders/modules/scripts due to not much information out there. I have no clue how to get the path to the data directory of the extension. If you want to use this loader right now you have to compile it yourself and change the path for the `ps4database.xml`

**Comment by 0x90h** [comment]
you need place it to path where can, for example \support\ps4database.xml

**Comment by jogolden** [comment]
I store the `ps4database.xml` in the data directory for the extension, there must be a way to programmatically get this path? So that it works on all operating systems too.

**Comment by 0x90h** [comment]
try
 static ResourceFile   findDataFileInAnyModule​(java.lang.String relativePath)    
Finds the first file that exists with the relative path in any module.

**Comment by 0x90h** [comment]
looks like this s*it code work
import ghidra.framework.Application;
	private String databasePath() throws IOException {
        String databasePath = Application.getModuleDataFile("ps4database.xml").toString();
        return databasePath;
    }

**Comment by jogolden** [comment]
my guy, pull request?
